name: Build on Windows Cygwin

on:
  push:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash.exe --login --norc -eo pipefail -o igncr '{0}'

    env:
      SHELLOPTS: igncr
      CHERE_INVOKING: 1
      CYGWIN_NOWINPATH: 1

    steps:
    - name: Configure git
      shell: cmd
      run: |
        git config --global core.autocrlf input

    - name: Checkout from git
      uses: actions/checkout@v4

    - name: Setup Cygwin
      uses: cygwin/cygwin-install-action@master
      with:
        platform: x64
        packages: make gcc-g++ dos2unix perl perl-Test-Harness

    - name: Install perl prerequisites
      run: |
        PERL_MM_USE_DEFAULT=1 cpan local::lib
        eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
        cpan -f Test::Harness
        cpan App::Prove Modern::Perl Path::Tiny Test::More 

    - name: Build
      run: |
        eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
        make

    - name: Run tests
      run: |
        eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
        make test
