name: Build on Ubuntu

on:
  push:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout from git
      uses: actions/checkout@v4

    - name: Cache multiple paths
      uses: actions/cache@v4
      with:
        path: |
          ~/perl5
        key: ${{ runner.os }}-cache1

    - name: Update apt 
      run: |
        sudo apt update

    - name: Install apt dependencies
      run: |
        sudo apt install -y cpanminus dos2unix libmodern-perl-perl liblocal-lib-perl libpath-tiny-perl

    - name: Install perl prerequisites
      run: |
        cpanm --local-lib=~/perl5 App::Prove Modern::Perl Path::Tiny Test::More 

    - name: Build
      shell: bash
      run: |
        eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
        make

    - name: Run tests
      shell: bash
      run: |
        eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
        make test
